version: '3.6'
services: 
    prod:
        build:
            context: .
            target: production
        ports: 
            - "80:80"
        environment: 
            REACT_APP_NODE_ENV: production
